# Setup
title: WikiTM
tagline: A wiki for tools used in and around robotics.
description: A wiki with tutorials and walkthroughs for technology and software used in robotics and related fields.
url: https://tejaswid.github.io/wikitm
paginate: 1
baseurl: https://tejaswid.github.io/wikitm/
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Sundara Tejaswi Digumarti and Krishna Manaswi Digumarti
  url: about.md
  email: 

# Custom vars
version: 1.0.0
github:
  repo: https://github.com/tejaswid/wikitm

# For navigation bar at the top
pages_list:       
  About: '/about'